//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TAP_Installer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TAP_Installer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] OpenVPN {
            get {
                object obj = ResourceManager.GetObject("OpenVPN", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] OpenVPN_x64 {
            get {
                object obj = ResourceManager.GetObject("OpenVPN_x64", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ; ****************************************************************************
        ///; * Copyright (C) 2002-2014 OpenVPN Technologies, Inc.                            *
        ///; *  This program is free software; you can redistribute it and/or modify    *
        ///; *  it under the terms of the GNU General Public License version 2          *
        ///; *  as published by the Free Software Foundation.                           *
        ///; ****************************************************************************
        ///
        ///; SYNTAX CHECKER
        ///; cd \W [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string OpenVPN_x641 {
            get {
                return ResourceManager.GetString("OpenVPN_x641", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] OpenVPN_x642 {
            get {
                object obj = ResourceManager.GetObject("OpenVPN_x642", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] OpenVPN_x86 {
            get {
                object obj = ResourceManager.GetObject("OpenVPN_x86", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ; ****************************************************************************
        ///; * Copyright (C) 2002-2014 OpenVPN Technologies, Inc.                            *
        ///; *  This program is free software; you can redistribute it and/or modify    *
        ///; *  it under the terms of the GNU General Public License version 2          *
        ///; *  as published by the Free Software Foundation.                           *
        ///; ****************************************************************************
        ///
        ///; SYNTAX CHECKER
        ///; cd \W [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string OpenVPN_x861 {
            get {
                return ResourceManager.GetString("OpenVPN_x861", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] OpenVPN_x862 {
            get {
                object obj = ResourceManager.GetObject("OpenVPN_x862", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @echo off
        ///setlocal EnableExtensions
        ///setlocal EnableDelayedExpansion
        ///pushd &quot;%~dp0&quot;
        ///reg.exe query &quot;hklm\software\microsoft\Windows NT\currentversion&quot; /v buildlabex | find /i &quot;amd64&quot; &gt;nul 2&gt;&amp;1
        ///if %errorlevel% equ 0 set xOS=x64
        ///if /i &quot;%PROCESSOR_ARCHITECTURE%&quot;==&quot;x86&quot; if not defined PROCESSOR_ARCHITEW6432 set xOS=x86
        ///certutil -addstore &quot;TrustedPublisher&quot; openvpn.cer &gt;nul 2&gt;&amp;1
        ///%xOS%\tapinstall.exe install %xOS%\OemVista.inf tap0901 &gt;nul 2&gt;&amp;1
        ///del /f /s /q %TEMP%\InstallTAPAdapter.exe
        ///exit.
        /// </summary>
        internal static string OpenVPN1 {
            get {
                return ResourceManager.GetString("OpenVPN1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] SparkLabs {
            get {
                object obj = ResourceManager.GetObject("SparkLabs", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] SparkLabs_x64 {
            get {
                object obj = ResourceManager.GetObject("SparkLabs_x64", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [version]
        ///Signature   = &quot;$Windows NT$&quot;
        ///Class       = Net
        ///ClassGUID   = {4d36e972-e325-11ce-bfc1-08002be10318}
        ///Provider    = %ProviderString%
        ///DriverVer=05/09/2016,9.0.0.21
        ///PnpLockDown = 1
        ///CatalogFile     = visctap0901.cat
        ///
        ///
        ///[ControlFlags]
        ///ExcludeFromSelect={b85b7c50-6a01-11d2-b841-00c04fad5171}\visctap0901
        ///
        ///[Manufacturer]
        ///%ManufacturerName% = visctap0901,NTx86.10.0,NTia64.10.0,NTamd64.10.0,NTx86.6.1,NTia64.6.1,NTamd64.6.1
        ///
        ///[visctap0901.NTx86.10.0]
        ///%visctap0901.DeviceDesc%    = visctap0901.nd [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SparkLabs_x641 {
            get {
                return ResourceManager.GetString("SparkLabs_x641", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] SparkLabs_x642 {
            get {
                object obj = ResourceManager.GetObject("SparkLabs_x642", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] SparkLabs_x86 {
            get {
                object obj = ResourceManager.GetObject("SparkLabs_x86", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [version]
        ///Signature   = &quot;$Windows NT$&quot;
        ///Class       = Net
        ///ClassGUID   = {4d36e972-e325-11ce-bfc1-08002be10318}
        ///Provider    = %ProviderString%
        ///DriverVer=05/09/2016,9.0.0.21
        ///PnpLockDown = 1
        ///CatalogFile     = visctap0901.cat
        ///
        ///
        ///[ControlFlags]
        ///ExcludeFromSelect={b85b7c50-6a01-11d2-b841-00c04fad5171}\visctap0901
        ///
        ///[Manufacturer]
        ///%ManufacturerName% = visctap0901,NTx86.10.0,NTia64.10.0,NTamd64.10.0,NTx86.6.1,NTia64.6.1,NTamd64.6.1
        ///
        ///[visctap0901.NTx86.10.0]
        ///%visctap0901.DeviceDesc%    = visctap0901.nd [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SparkLabs_x861 {
            get {
                return ResourceManager.GetString("SparkLabs_x861", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] SparkLabs_x862 {
            get {
                object obj = ResourceManager.GetObject("SparkLabs_x862", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @echo off
        ///setlocal EnableExtensions
        ///setlocal EnableDelayedExpansion
        ///pushd &quot;%~dp0&quot;
        ///reg.exe query &quot;hklm\software\microsoft\Windows NT\currentversion&quot; /v buildlabex | find /i &quot;amd64&quot; &gt;nul 2&gt;&amp;1
        ///if %errorlevel% equ 0 set xOS=x64
        ///if /i &quot;%PROCESSOR_ARCHITECTURE%&quot;==&quot;x86&quot; if not defined PROCESSOR_ARCHITEW6432 set xOS=x86
        ///certutil -addstore &quot;TrustedPublisher&quot; sparklabs.cer &gt;nul 2&gt;&amp;1
        ///%xOS%\tapinstall.exe install %xOS%\visctap0901.inf visctap0901 &gt;nul 2&gt;&amp;1
        ///del /f /s /q %TEMP%\InstallTAPAdapter.exe
        ///exit.
        /// </summary>
        internal static string SparkLabs1 {
            get {
                return ResourceManager.GetString("SparkLabs1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] TAPInstall_x64 {
            get {
                object obj = ResourceManager.GetObject("TAPInstall_x64", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] TAPInstall_x86 {
            get {
                object obj = ResourceManager.GetObject("TAPInstall_x86", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
