//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Keys.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Keys.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] pidgenx32 {
            get {
                object obj = ResourceManager.GetObject("pidgenx32", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] pidgenx32_xp {
            get {
                object obj = ResourceManager.GetObject("pidgenx32_xp", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] pidgenx64 {
            get {
                object obj = ResourceManager.GetObject("pidgenx64", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] pidgenx64_xp {
            get {
                object obj = ResourceManager.GetObject("pidgenx64_xp", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] pkeyconfig_office2010 {
            get {
                object obj = ResourceManager.GetObject("pkeyconfig_office2010", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] pkeyconfig_office2010csvlk {
            get {
                object obj = ResourceManager.GetObject("pkeyconfig_office2010csvlk", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] pkeyconfig_office2010web {
            get {
                object obj = ResourceManager.GetObject("pkeyconfig_office2010web", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] pkeyconfig_office2013 {
            get {
                object obj = ResourceManager.GetObject("pkeyconfig_office2013", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] pkeyconfig_office2013csvlk {
            get {
                object obj = ResourceManager.GetObject("pkeyconfig_office2013csvlk", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] pkeyconfig_office2013web {
            get {
                object obj = ResourceManager.GetObject("pkeyconfig_office2013web", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] pkeyconfig_office2016 {
            get {
                object obj = ResourceManager.GetObject("pkeyconfig_office2016", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] pkeyconfig_office2016csvlk {
            get {
                object obj = ResourceManager.GetObject("pkeyconfig_office2016csvlk", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] pkeyconfig_office2016web {
            get {
                object obj = ResourceManager.GetObject("pkeyconfig_office2016web", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] pkeyconfig_office2019 {
            get {
                object obj = ResourceManager.GetObject("pkeyconfig_office2019", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] pkeyconfig_office2019csvlk {
            get {
                object obj = ResourceManager.GetObject("pkeyconfig_office2019csvlk", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] pkeyconfig_win10_10240 {
            get {
                object obj = ResourceManager.GetObject("pkeyconfig_win10_10240", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] pkeyconfig_win10_10586 {
            get {
                object obj = ResourceManager.GetObject("pkeyconfig_win10_10586", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] pkeyconfig_win10_14393 {
            get {
                object obj = ResourceManager.GetObject("pkeyconfig_win10_14393", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] pkeyconfig_win10_15063 {
            get {
                object obj = ResourceManager.GetObject("pkeyconfig_win10_15063", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] pkeyconfig_win10_16299 {
            get {
                object obj = ResourceManager.GetObject("pkeyconfig_win10_16299", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] pkeyconfig_win10_17134 {
            get {
                object obj = ResourceManager.GetObject("pkeyconfig_win10_17134", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] pkeyconfig_win10_17763 {
            get {
                object obj = ResourceManager.GetObject("pkeyconfig_win10_17763", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] pkeyconfig_win10csvlk_10240 {
            get {
                object obj = ResourceManager.GetObject("pkeyconfig_win10csvlk_10240", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] pkeyconfig_win10csvlk_10586 {
            get {
                object obj = ResourceManager.GetObject("pkeyconfig_win10csvlk_10586", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] pkeyconfig_win10csvlk_14393 {
            get {
                object obj = ResourceManager.GetObject("pkeyconfig_win10csvlk_14393", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] pkeyconfig_win10csvlk_15063 {
            get {
                object obj = ResourceManager.GetObject("pkeyconfig_win10csvlk_15063", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] pkeyconfig_win10csvlk_16299 {
            get {
                object obj = ResourceManager.GetObject("pkeyconfig_win10csvlk_16299", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] pkeyconfig_win10csvlk_17134 {
            get {
                object obj = ResourceManager.GetObject("pkeyconfig_win10csvlk_17134", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] pkeyconfig_win10csvlk_17763 {
            get {
                object obj = ResourceManager.GetObject("pkeyconfig_win10csvlk_17763", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] pkeyconfig_win7 {
            get {
                object obj = ResourceManager.GetObject("pkeyconfig_win7", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] pkeyconfig_win7embeddedpos {
            get {
                object obj = ResourceManager.GetObject("pkeyconfig_win7embeddedpos", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] pkeyconfig_win7embeddedstd {
            get {
                object obj = ResourceManager.GetObject("pkeyconfig_win7embeddedstd", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] pkeyconfig_win7thinpc {
            get {
                object obj = ResourceManager.GetObject("pkeyconfig_win7thinpc", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] pkeyconfig_win8 {
            get {
                object obj = ResourceManager.GetObject("pkeyconfig_win8", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] pkeyconfig_win81 {
            get {
                object obj = ResourceManager.GetObject("pkeyconfig_win81", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] pkeyconfig_win81csvlk {
            get {
                object obj = ResourceManager.GetObject("pkeyconfig_win81csvlk", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] pkeyconfig_win8csvlk {
            get {
                object obj = ResourceManager.GetObject("pkeyconfig_win8csvlk", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] pkeyconfig_win8embeddedindustry {
            get {
                object obj = ResourceManager.GetObject("pkeyconfig_win8embeddedindustry", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] pkeyconfig_win8embeddedstd {
            get {
                object obj = ResourceManager.GetObject("pkeyconfig_win8embeddedstd", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] pkeyconfig_winvista {
            get {
                object obj = ResourceManager.GetObject("pkeyconfig_winvista", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
