//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoKMS.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("%WINDIR%\\AutoKMS")]
        public string AutoKMSPath {
            get {
                return ((string)(this["AutoKMSPath"]));
            }
            set {
                this["AutoKMSPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("%WINDIR%\\AutoRearm")]
        public string AutoRearmPath {
            get {
                return ((string)(this["AutoRearmPath"]));
            }
            set {
                this["AutoRearmPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("%WINDIR%\\KMSServerService")]
        public string KMSServerServicePath {
            get {
                return ((string)(this["KMSServerServicePath"]));
            }
            set {
                this["KMSServerServicePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ReuseKMSPID")]
        public string KMSPIDOffice {
            get {
                return ((string)(this["KMSPIDOffice"]));
            }
            set {
                this["KMSPIDOffice"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ReuseKMSPID")]
        public string KMSPIDWindows {
            get {
                return ((string)(this["KMSPIDWindows"]));
            }
            set {
                this["KMSPIDWindows"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1688")]
        public int KMSPortOffice {
            get {
                return ((int)(this["KMSPortOffice"]));
            }
            set {
                this["KMSPortOffice"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1688")]
        public int KMSPortWindows {
            get {
                return ((int)(this["KMSPortWindows"]));
            }
            set {
                this["KMSPortWindows"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("127.0.0.2")]
        public string KMSServerOffice {
            get {
                return ((string)(this["KMSServerOffice"]));
            }
            set {
                this["KMSServerOffice"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("127.0.0.2")]
        public string KMSServerWindows {
            get {
                return ((string)(this["KMSServerWindows"]));
            }
            set {
                this["KMSServerWindows"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool RemoveKMSConnection {
            get {
                return ((bool)(this["RemoveKMSConnection"]));
            }
            set {
                this["RemoveKMSConnection"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UseKMSEmulator {
            get {
                return ((bool)(this["UseKMSEmulator"]));
            }
            set {
                this["UseKMSEmulator"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShowCMID {
            get {
                return ((bool)(this["ShowCMID"]));
            }
            set {
                this["ShowCMID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShowUnlicensed {
            get {
                return ((bool)(this["ShowUnlicensed"]));
            }
            set {
                this["ShowUnlicensed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool KillProcessOnPort {
            get {
                return ((bool)(this["KillProcessOnPort"]));
            }
            set {
                this["KillProcessOnPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".\\Backups")]
        public string LicenseBackupsPath {
            get {
                return ((string)(this["LicenseBackupsPath"]));
            }
            set {
                this["LicenseBackupsPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10.3.0.1")]
        public string LocalHostBypassIPAddress {
            get {
                return ((string)(this["LocalHostBypassIPAddress"]));
            }
            set {
                this["LocalHostBypassIPAddress"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("255.255.255.0")]
        public string LocalHostBypassIPSubnet {
            get {
                return ((string)(this["LocalHostBypassIPSubnet"]));
            }
            set {
                this["LocalHostBypassIPSubnet"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool LocalHostBypassUseTAPAdapter {
            get {
                return ((bool)(this["LocalHostBypassUseTAPAdapter"]));
            }
            set {
                this["LocalHostBypassUseTAPAdapter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool LocalHostBypassUseWinDivertClient {
            get {
                return ((bool)(this["LocalHostBypassUseWinDivertClient"]));
            }
            set {
                this["LocalHostBypassUseWinDivertClient"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool LocalHostBypassUseDLLInjection {
            get {
                return ((bool)(this["LocalHostBypassUseDLLInjection"]));
            }
            set {
                this["LocalHostBypassUseDLLInjection"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("364F463A8863D35F")]
        public string KMSHardwareID {
            get {
                return ((string)(this["KMSHardwareID"]));
            }
            set {
                this["KMSHardwareID"] = value;
            }
        }
    }
}
